### ISSUE TITLE
.jpg'd chip art.

### ISSUE THREAD

**Issue by TerminusEst13** [SHNecro/ShanghaiJAR#5]
Not much to say. Some chip art has been rendered as a .jpg due to being ripped from stream/twitter, like DruidMan/ShellHockey.
Here's some prospective replacements.

https://i.imgur.com/uRZdwYW.png / https://i.imgur.com/1snl5pz.png
Here's my take on a cleaned-up DruidMan v1, as done for the NetBattlers: Genso Network tabletop expansion.
**EDIT:** And some expansions for v2/v3/X done by Lucina.

https://i.imgur.com/UZvRzR3.png
Lucina / ThatRandomSpriter is cleaning up PA chips. She's working on cleaning up the others.

**Comment by SHNecro** [comment]
Thank you to the both of you, I'll get these in once I wrap up the current batch of changes.

The PA art I'll see if I can work into the Library, I've actually already rewritten that page in order to support the more flexible chipnumber/PA system.

**Comment by ThatRandomSpriter** [comment]
Hey there, this is ThatRandomSpriter aka Lucina. I thought I'd jump in and let you know that I've finally finished the Battle Chip art restoration for the lost Program Advance Battle Chips. The link provided will contain the image file of all 29 Battle Chips that Terminus had shared with me. https://imgur.com/a/zaFNNtH

If there is any other chip art that suffers from jpeg artifacting, do let me know and I'll work on restoring it when I can.

**Comment by SHNecro** [comment]
Cleaned sprites implemented, with PA page upgraded to show them
14a81f37f0f7b0762f9eaf3ecc0ba0635a30cf86
f1d99fea7a4d85de49156c742bc8fe0de2aa5567
